### ISSUE TITLE
'HiveApi' object has no attribute 'log'

### ISSUE THREAD

**Issue by samwatling** [Pyhive/Pyhiveapi#10]
I'm trying to call the set_state method and receive the following error:

File "/Users/samwatling/.pyenv/versions/3.8.5/lib/python3.8/site-packages/pyhiveapi/hive_api.py", line 205, in set_state
    self.log.log(
AttributeError: 'HiveApi' object has no attribute 'log'

I'm already logged in and have access tokens. Running latest version of pyhiveapi from pip. Python 3.8.5.

Code snippet that generates the above error:

import pyhiveapi as Hive
api = Hive.HiveApi()
doStuff = api.set_state(self.tokens["token"], inHiveDeviceType, DeviceID, status="ON")

**Comment by KJonline** [comment]
@samwatling  this should be fixed in version 0.3.3
