### ISSUE TITLE
Example Expansion

### ISSUE THREAD

**Issue by andriodious** [Pyhive/Pyhiveapi#15]
The examples work great thanks but I'm still trying to get my head around the API.

Could the examples in the readme please be extended to:

1) Add examples for manipulating lights and plugs for example identify and toggle a given device
2) When to refresh tokens

Many thanks

**Comment by andriodious** [comment]
Many thanks indeed for expanding the readme to include comprehensive examples -- this is great and much appreciated!

Before I close this issue please can I just ask for some clarifications by way of examples regarding use of tokens:

1. When is it desirable to use session tokens vs logging in without?
2. When using tokens, how can one check that they are still valid (vs calling refresh tokens at arbitrary intervals) ?
3. What is the relation in the example between the data object and the session object

Thanks again

**Comment by KJonline** [comment]
@andriodious 

the session version takes care of everything for you and to update the tokens you would call update_data which checks for you if the tokens need updating when they do it will update them for you.

The purpose of the API version is for people who to have more control over the data and what they want to do with it. Using that method you have to right your own functions to process incoming data and out going data.

if using the api way the time the tokens last for is in the response when getting the tokens back from the api.


Once start session has run it creates a deviceList all the examples are showing is how to get a device from that list and use its functions.

**Comment by aashram** [comment]
Love the examples and I have it all working great. 
Is there way to set the schedule for the week if its been changed ? I can view the schedule I know but can set it too ?

**Comment by andriodious** [comment]
> @andriodious
> 
> 1
> the session version takes care of everything for you and to update the tokens you would call update_data which checks for you if the tokens need updating when they do it will update them for you.
> 
> The purpose of the API version is for people who to have more control over the data and what they want to do with it. Using that method you have to right your own functions to process incoming data and out going data.
> 
> 2
> if using the api way the time the tokens last for is in the response when getting the tokens back from the api.
> 
> 3
> Once start session has run it creates a deviceList all the examples are showing is how to get a device from that list and use its functions.

Perfect, many thanks
