### ISSUE TITLE
[BUG] pyhiveapi no longer connecting and returning data from HIVE

### ISSUE THREAD

**Issue by DerekStarling** [Pyhive/Pyhiveapi#6]
**Describe the bug**
The api has completely stopped communicating with Hive.  It was OK up until 2nd October 2020.  Since midday (GMT) that day, I have received no updates.  I've seen similar issues reported on Hive fora and have been waiting for an update, but maybe no-one had actually formalized the issue here.

**Expected behavior**
Data returned from the Hive.  My interest being house temperature, target and external temperature.

**Additional context**
# environment
Raspbery Pi - Buster
Python 3.7.3

pi@raspberrypi:~ $ pip3 show pyhiveapi
Name: pyhiveapi
Version: 0.2.20.2
Summary: A Python library to interface with the Hive API
Home-page: https://github.com/Rendili/pyhiveapi
Author: Rendili
Author-email: rendili@outlook.com
License: MIT
Location: /home/pi/.local/lib/python3.7/site-packages
Requires: 
Required-by: 

## also tested on MacOS with python 3.8 and same level of pyhiveapi 0.2.20.2 with same results

# Test run results
Running Pyhiveapi/examples/pyhiveapi_example_1.py with my credential resulted in the following output

Attempt to log in to the Hive API

Attempt to get Outside temperature
Outside Temperature = 0.0

Update Data
Update Data result = False
An update result of False = data is cached and a Hive API call was not made
An update result of True = Hive API called data was retrieved and cached

**Comment by KJonline** [comment]
@DerekStarling we are aware of this issue and work is underway to fix this very soon.

**Comment by KJonline** [comment]
Fixed with version 0.3 (Current only support for Async, Sync version is WIP)
